# Generated by Django 4.2.4 on 2023-08-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
